# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6e5b256cf108d3db702fb58270a2bbdc944a44a55127f1b474db093ec333552189bb27e2c5e76f6a950ec0448cbc40ee192fe42749d620c6f507861440ed6254

test:
  secret_key_base: 6f9cb565e7ba09634d0de312b1ba8ea25d925f314d8ef4f5049a32c5bed84c1de83b5d0fc5d031d3f9be30c28d1108e61ffb66bc65285ad1c9ff35d33eb2ae53

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
